spack:
  specs:
  - gcc@14 languages:='c,c++'
  - python@3.12
  - py-cython
  - py-numpy
  - py-pip
  - py-jinja2
  - netcdf-cxx4
  - openmpi
  - sundials+petsc+hypre+mpi~examples~examples-install
  - petsc+double+fftw+hdf5+hypre+mpi~fortran
  - slepc

  concretizer:
    unify: true
  
  view: /opt/views/view

  config:
    install_tree: /opt/software
